summary: fix persist test flake
```
     def test_summary_persist(node_factory):
          # Set a low PeerThread interval so we can test quickly.
          opts = {"summary-availability-interval": 0.5, "may_reconnect": True}
          opts.update(pluginopt)
          l1, l2 = node_factory.line_graph(2, opts=opts)

          # when
          l1.daemon.logsearch_start = 0
          l1.daemon.wait_for_log("Creating a new datastore")
          l1.daemon.wait_for_log("Peerstate wrote to datastore")
          s1 = l1.rpc.summary()
          l2.stop()
          l1.restart()
          assert l1.daemon.is_in_log("Reopened datastore")
          l1.daemon.logsearch_start = len(l1.daemon.logs)
          l1.daemon.wait_for_log("Peerstate wrote to datastore")
          s2 = l1.rpc.summary()

          # then
          avail1 = int(re.search(" ([0-9]*)% ", s1["channels"][2]).group(1))
          avail2 = int(re.search(" ([0-9]*)% ", s2["channels"][2]).group(1))
  >       assert avail1 == 100
  E       assert 88 == 100

  test_summary.py:199: AssertionError
```

The first tick could happen while the peers were not yet connected